spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    format-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE


server:
  servlet:
    context-path: /uaa
  port: 8081
